### ISSUE TITLE
Website Not Working

### ISSUE THREAD

**Issue by christos-efthymiou** [cmbi/xssp-api#106]
I used the site (https://www3.cmbi.umcn.nl/xssp/) a couple months ago, but it no longer works. When I enter a PDB ID and run the program, I get the following error: 
---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/xssp_api/factory.py", line 143, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/xssp_api/tasks.py", line 215, in get_dssp
    raise RuntimeError("File not found: '{}'".format(dssp_path))
RuntimeError: File not found: '/mnt/chelonium/dssp/7kxy.dssp'
---

I have tried this several times over the course of a few days in different browsers and it still does not work.

**Comment by cbaakman** [comment]
Sorry for the fact that this dssp file was missing. It's fixed now. You can enter 7kxy to get your dssp file.
